language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
  include:
    - os: osx
      rust: stable
    - os: osx
      rust: beta
    - os: osx
      rust: nightly
    - os: linux
      rust: stable
      env: TARGET=i686-unknown-linux-gnu
      addons:
        apt:
          update: true
          packages:
            - gcc-multilib
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-musl
    - os: linux
      rust: stable
      env: TARGET=i686-unknown-linux-musl
    - os: linux
      rust: stable
      env: TARGET=aarch64-unknown-linux-gnu NO_TEST=1 LINKER="aarch64-linux-gnu-gcc" AR="aarch64-linux-gnu-ar"
      addons:
        apt:
          update: true
          packages:
            - libc6-dev-arm64-cross
            - gcc-aarch64-linux-gnu
    - os: linux
      rust: stable
      env: TARGET=arm-unknown-linux-gnueabihf NO_TEST=1 LINKER="arm-linux-gnueabihf-gcc" AR="arm-linux-gnueabihf-ar"
      addons:
        apt:
          update: true
          packages:
            - libc6-dev-armhf-cross
            - gcc-arm-linux-gnueabihf
install:
  - set | egrep '^TARGET' || TARGET=$(rustup target list | grep installed | awk '{print $1}')
  - rustup target add ${TARGET}
script:
  - test -n "${NO_TEST}" || RUST_BACKTRACE=1 cargo test --verbose --all --target ${TARGET}
before_deploy:
  - mkdir -p .cargo
  - test -z "${LINKER}" || echo -e "[target.${TARGET}]\nlinker = \"${LINKER}\"\nar = \"${AR}\"\n" >> .cargo/config
  - cargo build --release --verbose --all --target ${TARGET}
  - PACKAGE_NAME=regtail-${TRAVIS_TAG}-${TARGET}
  - mkdir ${PACKAGE_NAME}
  - cp target/${TARGET}/release/regtail LICENSE README.md ${PACKAGE_NAME}
  - tar czf ${PACKAGE_NAME}.tar.gz ${PACKAGE_NAME}
deploy:
  provider: releases
  api_key:
    secure: FCOLjxc5+74I8mjtjHoxKlrrpffPP7fXjVoUEhlW7CNMhjv/ZbcGyMNZRtZ+OojIUqA6XcdsFNYBaXEwEUjUP835aiGo6gcpOq9SjFNkZZJ5QmZ6WgcmZQPnFkQ4rwMW0/2Mnj81c2MIbeN3B1cJrM7JzZDR8FGf/2tjrIoILMOUMgUUGcn1xNDqZpNnBuQnx1Z0Tdhm24ekDI3q4rMtEtoKC3yXNJ5UYBb5xxI1EwUnbLUCE7pSOFpCU6gr00jyPcMHaU+lwS9u9WVGFBw6fJ2wpYx1+SyS0NIa8sWBucVf72/jovOJLIQFb3OQi+IAvT1H1Pcpt6hCB7P2OSubBi0nUIQCtHKoZrRGzkQU4gHZTDjNj7aSYx1yZ22RQIuY6qfHHMOGSmCLXEB2AW6TlNdgJNyQ0n9smwVhVsgX7nb36zwkKZi79LJvnM/qhHT4YNY+rKc5KxC0yTBLypKLprkOejsUbr/oz05r7A6dU6SRQnoqdeB8h60HmS9NTm+VhJC1gbftHxzKpVS/ktNZC97gcHLQ3R/em9cNF9m9ktkRF93XFUSYYfOt0aqLk7Mci5cZViQm8ORhNqPDZg4sQ/hbIXH9DXitwzlcU+KCE7hqIacwl/58sl3kEp5Ies5ssuI/zdZAX/HwPIBvIupmK1AbA77t7ZcLVcotKoe87X4=
  file: regtail-${TRAVIS_TAG}-${TARGET}.tar.gz
  on:
    repo: StoneDot/regtail
    tags: true
    condition: ${TRAVIS_RUST_VERSION} = stable
  skip_cleanup: true
