[package]
name = "regtail"
version = "0.0.2"
authors = ["Hiroaki Goto <goto.inct@gmail.com>"]
edition = "2018"

[dependencies]
notify = "4.0"
walkdir = "2"
regex = "1"
lazy_static = "1.2.0"
pathdiff = "0.1.0"
clap = "2.32.0"
lru = "0.1.11"

[profile.release]
opt-level = 3
lto = true